import "./globals.css";
import type { Metadata } from "next";
import { RocknRoll_One } from "next/font/google";

const rocknRoll_One = RocknRoll_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rocknRoll_One.className}>{children}</body>
    </html>
  );
}
